# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{stat_mon}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Wagner"]
  s.date = %q{2010-10-29}
  s.default_executable = %q{statmon}
  s.description = %q{Easy way to monitor and log statistics on your server.}
  s.email = %q{mwagner@digitalinsites.com}
  s.executables = ["statmon"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "VERSION",
     "bin/statmon",
     "lib/stat_mon.rb",
     "lib/stat_mon/cli/execute.rb",
     "lib/stat_mon/exceptions.rb",
     "lib/stat_mon/listener.rb",
     "lib/stat_mon/log.rb",
     "lib/stat_mon/task.rb",
     "spec/spec_helper.rb",
     "spec/stat_mon/log_spec.rb",
     "spec/stat_mon/task_spec.rb",
     "spec/stat_mon_spec.rb"
  ]
  s.homepage = %q{http://github.com/mikewagner/statmon}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Easy way to monitor and log statistics on your server.}
  s.test_files = [
    "spec/stat_mon/log_spec.rb",
     "spec/stat_mon/task_spec.rb",
     "spec/spec_helper.rb",
     "spec/stat_mon_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<eventmachine>, [">= 0.12.10"])
      s.add_development_dependency(%q<rspec-core>, [">= 2.0.1"])
      s.add_development_dependency(%q<rspec-expectations>, [">= 2.0.1"])
    else
      s.add_dependency(%q<eventmachine>, [">= 0.12.10"])
      s.add_dependency(%q<rspec-core>, [">= 2.0.1"])
      s.add_dependency(%q<rspec-expectations>, [">= 2.0.1"])
    end
  else
    s.add_dependency(%q<eventmachine>, [">= 0.12.10"])
    s.add_dependency(%q<rspec-core>, [">= 2.0.1"])
    s.add_dependency(%q<rspec-expectations>, [">= 2.0.1"])
  end
end

